### ISSUE TITLE
Too coarse-grained...

### ISSUE THREAD

**Issue by montagist** [mvillaloboz/open-source-cs-degree#15]
I like where your heads at but if I see something labeled the "open source cs degree" online, I expect it to be more fine-grained than this. By this I mean, what concepts and ideas do -you- think/know are important to CS and in which of the complete video courses linked to would we find these things? I do understand, though, that some of these courses are fundamental from start to finish, but even then I feel you perhaps could use some sort of overarching guidance in this as the person competes each course-link. Otherwise this just feels like a google search of "free computer science courses online"

Just my two cents. Take it as you will :)

**Comment by fouaddev** [comment]
The list is well structured by order, just follow it and you'll be all set towards a free bachelor degree in computer science from top universities. The only thing you'll miss is the actual degree paper lol which is not nesessary as most developers/programmers are sf taught and don't have a degree anyways, and that's why hiring managers do hire them without requiring a degree, as long as you know the field.
